name: Task Scheduler

on:
  schedule:
    # Run every minute
    - cron: '*/1 * * * *'

jobs:
  create-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Adjust to your .NET version

    - name: Install dependencies
      run: dotnet restore ./TaskFunctionApp.sln

    - name: Install Azure Functions Core Tools v4
      run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

    - name: Make create_tasks.sh executable
      run: chmod +x ./scripts/create_tasks.sh  

    - name: Run task creation script
      run: |
        ./scripts/create_tasks.sh # Replace this with your actual script to handle time-specific tasks

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Function App
      run: |
        func azure functionapp publish Cse415FinalProjectFuncBDO \
          --resource-group Cse415FinalProject \
          --subscription 1cb8856f-3930-428d-91b2-5553d77f6b53 \
          --dotnet-isolated \
          --force
